-- MySQL Script generated by MySQL Workbench
-- Thu Aug 17 12:48:03 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema restauranter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restauranter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restauranter` DEFAULT CHARACTER SET utf8 ;
USE `restauranter` ;

-- -----------------------------------------------------
-- Table `restauranter`.`Reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restauranter`.`Reviews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reviewer` VARCHAR(255) NULL,
  `restaurant` VARCHAR(255) NULL,
  `review` TEXT NULL,
  `dateofvisit` DATE NULL,
  `stars` TEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
